---
title: "MRC Examples"
format: html
toc: true
---

## Setup
```{r}
#| label: setup
#| message: false
#| warning: false
library("tidyverse")
library("ds4ling")
library("untidydata")
library("broom")
library("emmeans")
```

## Tidy Data
```{r}
#| label: explore-data

ld <- language_diversity %>%
  mutate_if(is.character, as.factor) #is.character 

summary(ld)
dim(ld)
str(ld)
glimpse(ld)
#View(ld)

#ld %>%
#  ggplot() +
#  aes(x = Continent, y = Value) +
#  geom_point()

ld_wide <- ld %>%
  pivot_wider(
    names_from = "Measurement",
    values_from = "Value"
  ) %>%
  mutate(
    lang_log = log(Langs),
    area_log = log(Area),
    pop_log = log(Population)
  )

#View(ld_wide)
```

## Analyses
```{r}
#| label: fit-model

mean(ld_wide$lan_log)

mod_0 <- lm(lang_log ~ 1, data=ld_wide)
summary(mod_0)

mod_1 <- lm(lang_log ~ 1 + pop_log, data=ld_wide)
summary(mod_1)

#intercept = 0.338: "when pop_log is 0, value of lang_log is 0.338"
#pop_log = 0.367: "a one unit increase in pop_log corresponds to an 0.367 unit increase in lang_log"

#add in area_log
mod_2 <- lm(lang_log ~ 1 + pop_log + area_log, data=ld_wide)
summary(mod_2)

#intercept = -1.0096: "" 
#pop_log = 0.2946: "a one unit increase in pop_log corresponds to a 0.2946 unit increase in lang_log, holding area_log constant"
#area_log = 0.1557: "a one unit increase in area_log corresponds to a 0.1557 unit increase in lang_log, holding pop_log constant"

mod_3 <- lm(lang_log  ~ 1 + pop_log*area_log, data=ld_wide)
#can also write as:
#mod_3 <- lm(lang_log ~ 1 + pop_log + area_log + pop_log:area_log, data=ld_wide
summary(mod_3)
```

## Tables and Plots

Hello! Please appreciate @tbl-model1 and @tbl-model3

```{r}
#| label: tbl-model1
#| tbl-cap: "hello"
tidy(mod_1) %>%
  knitr::kable(format="pandoc")
```

```{r}
#| label: tbl-model3
#| tbl-cap: "hello"
# always keep the first part of this label tbl!!

tidy(mod_3) %>%
  knitr::kable(format="pandoc") #:: uses a function (in this case kable()) from a package (in this case knitr) without loading the entire prackage
#kable formats it for latex or html
```

```{r}
emmeans(
  object = mod_1,
  specs = ~ pop_log,
  at = list(pop_log = seq(0,20,by=1))
)

emmeans(
  object = mod_3,
  specs = ~ pop_log*area_log,
  at = list(pop_log = c(0,10,20),
            area_log = c(0,10,20))
)
#emmean stands for estimated marginal mean
#gives us where points would fall on a line at our specified values (here, it's 0,10,20). also incoporates doubt; it's a 95% confidence interval
```

```{r}
# NMC examples using forward selection

# 1. From the mtcars dataframe select the solumns 'mpg', 'wt', and 'drat'
# and assign this subset of columns to a new object called 'my_cars'

mtcars
my_cars <- mtcars %>%
  select(mpg, wt, drat)

my_cars

#Run the following models:

mod_null <- lm(mpg ~ 1, data = my_cars)
mod_wt   <- lm(mpg ~ 1 + wt, data = my_cars)
mod_add  <- lm(mpg ~ 1+ wt + drat, data = my_cars)
mod_int  <- lm(mpg ~ 1 + wt + drat + wt:drat, data = my_cars)

# 2. Look at the summary of mod_null. What does the intercept tell you?

summary(mod_null)

#intercept = 20.091 --> mean of mpg is ~20.091
#when you fit an intercept-only model, it gives you the mean of the dependent variable
#adding in other effects: if i add another predictor/ more info, can i imporve the model? in this example: can we determine mpg with more accuracy?

# 3. Look at the summary of mod_wt. What does the summary tell you?
 
summary(mod_wt)
# intercept = 37.285: when wt=0, mpg = 37.285
# wt = -5.3445: a 1-unit increase in wt is associated with a 5.3445 decrease in mpg
# standard error: withing above and below 1.8776 of 37.2851, within above and below 0.5591 of -5.3445
# Pr(>|t|) aka p-val: the estimate is not statistically equal to zero
# Adjusted R-squared=0.7446: This model can account for about 74.46 of the variance
# F-stat p-val: at least one of the predictors is statistically significant

# 4. Use a nested model comparison to test the additive effect of 'drat' (hint: use anova() function)

anova(mod_wt, mod_add)
summary(mod_wt)
summary(mod_add)

#F ratio below 1, don't need to add drat to make model more accurate

# 5. Test interaction term using a NMC (nesting model comparison) and write out the important info in a comment below

anova(mod_add, mod_int)

#F ratio above 1, so the interaction between mpg and drat is something we can add to make the model more accurate
#The interaction was significant (F(1) = 5.41 (F(1) = f-ratio with 1 degree of freedom, 5.41 > 1, p < 0.03). The effect of _ on mpg depends on __


```